project:
  type: website

website:
  title: "iRODS4R"
  site-url: https://fairelabs.github.io/iRODS4R
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FAIReLABS
      - icon: rss
        href: index.xml
      - text: R-bloggers
        href: https://www.r-bloggers.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

