project:
  type: website

website:
  title: "iRODS4R"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FAIReLABS
      - icon: twitter
        href: https://twitter.com/irods
      - icon: r-bloggers
        href: https://www.r-bloggers.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

